#include "main.h"
#include "application_layer.h"

int main(void)
{
    // STM32 HAL and peripherals init normally generated by CubeMX
    // Custom initialization ...

    while (1)
    {
        APP_Update();
        // Here would be UART polling or event-based handler
    }
    // Should never reach here
    return 0;
}
