/**
 * @file system_init.c
 * @brief System Startup / Initialisation implementation.
 *
 * Traces: SWE-REQ-020
 * Platform: STM32F407G-DISC1 / STM32 HAL
 *
 * Calls HAL_Init, SystemClock_Config (expected from CubeMX), and
 * initialises every software unit in the correct order.
 */

#include "system_init.h"
#include "stm32f4xx_hal.h"
#include "command_parser.h"
#include "feedback_processor.h"
#include "flap_control_logic.h"
#include "led_status_handler.h"
#include "motor_driver.h"

/* ---- External CubeMX-generated functions ---- */

/**
 * @brief System clock configuration (generated by STM32CubeMX).
 *        Must be provided by the project / CubeMX output.
 */
extern void SystemClock_Config(void);

/**
 * @brief GPIO initialisation (generated by STM32CubeMX).
 *        Configures all GPIO pins used by motor, LEDs, etc.
 */
extern void MX_GPIO_Init(void);

/**
 * @brief USART2 initialisation (generated by STM32CubeMX).
 */
extern void MX_USART2_UART_Init(void);

/**
 * @brief ADC1 initialisation (generated by STM32CubeMX).
 */
extern void MX_ADC1_Init(void);

/**
 * @brief TIM2 initialisation for PWM (generated by STM32CubeMX).
 */
extern void MX_TIM2_Init(void);

/* ---- Public API ---- */

void system_init(void)
{
    /* 1. HAL low-level init */
    HAL_Init();

    /* 2. Configure system clock */
    SystemClock_Config();

    /* 3. Initialise peripherals (CubeMX generated) */
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();
    MX_TIM2_Init();

    /* 4. Initialise software units [SWE-REQ-020] */
    command_parser_init();
    feedback_processor_init();
    motor_driver_init();        /* Ensures motor is stopped */
    led_status_init();          /* Power LED ON, position LEDs OFF */
    flap_control_init();
}
