/**
 * @file system_init.c
 * @brief System Startup / Initialisation implementation.
 *
 * Traces: SWE-REQ-020
 *
 * Platform: STM32F407G-DISC1, STM32 HAL, bare-metal
 *
 * This module calls STM32 HAL init, configures clocks and peripherals,
 * then initialises every software unit and sets initial safe states.
 *
 * NOTE: Peripheral configuration functions (MX_GPIO_Init, MX_USART2_UART_Init,
 *       MX_ADC1_Init, MX_TIM2_Init) are assumed generated by STM32CubeMX and
 *       linked from the project. Prototypes declared here as extern.
 */

#include "system_init.h"
#include "command_parser.h"
#include "flap_control_logic.h"
#include "feedback_processor.h"
#include "led_status_handler.h"
#include "motor_driver.h"
#include "stm32f4xx_hal.h"

/* ---- CubeMX-generated peripheral init prototypes ---- */

extern void SystemClock_Config(void);
extern void MX_GPIO_Init(void);
extern void MX_USART2_UART_Init(void);
extern void MX_ADC1_Init(void);
extern void MX_TIM2_Init(void);

/* ================================================================== */

void SystemInit_Run(void)
{
    /* 1. HAL low-level init (SWE-REQ-020) */
    HAL_Init();

    /* 2. Configure system clock */
    SystemClock_Config();

    /* 3. Peripheral init (GPIO, UART, ADC, PWM timer) */
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();
    MX_TIM2_Init();

    /* 4. Software unit initialisation (SWE-REQ-020) */
    CommandParser_Init();
    FeedbackProcessor_Init();
    FlapControl_Init();
    LedStatus_Init();        /* Power LED ON (SWE-REQ-012) */
    MotorDriver_Init();      /* Motor OFF safe state (SWE-REQ-008) */
}
